---
- hosts: localhost
  become: yes
  become_method: sudo

  tasks:
    - name: "Add {{ item.name }} repo to apt"
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: yes
      loop:
        - { name: 'Gazebo', repo: 'deb http://packages.osrfoundation.org/gazebo/ubuntu-stable' }
        - { name: 'Java/Oracle', repo: 'ppa:webupd8team/java'} # Required for oracle-java8-installer

    # Adds whatever key it finds at the URL to apt's keyring.
    - name: "Add Gazebo apt key"
      apt_key:
        url: "http://packages.osrfoundation.org/gazebo.key"
        state: present

    - name: "Install {{ item.name }}"
      package:
        name: "{{ item.name }}"
        state: present
      loop:
        - { name: "oracle-java8-installer" }
        - { name: "clang-format"  } # Required for a later script (may remove if can find way around)
        - { name: "gazebo9" }
        - { name: "gazebo9-dev" } # Added pkg for developers
        # - { name: "libzmq3-dev"   } # Is pulled later?
        #- { name: "openjdk-11-jdk" } # May actually need java 8 not 11 TODO: Verify


...